### PR TITLE
hero_section

### PR DESCRIPTION
**Pull request by RSN601KRI**

### CODE REVIEW

**Review by MSami625 — APPROVED** [review]
good.

**Comment by RSN601KRI** [comment]
Thank you😊

**Comment by MSami625** [comment]
There were lot of merge conflicts . In future always pull the latest code from repo before contributing . you need to regularly pull latest code so that  conflicts dont happen and locally confirm everything is working . then make a PR.

**Comment by RSN601KRI** [comment]
Thanks for the feedback. I understand the importance of avoiding merge conflicts. I'll consistently pull the latest code, locally test it, and then submit pull requests. Your advice is appreciated and I'm committed to improving my workflow for smoother collaboration.😊

**Pull request merged**
