### PR TITLE
navlink routing done

### PR DESCRIPTION
**Pull request by vishnu552**
navlink routing done using react-rounter and i created a new header component and place all the navbar code in to header component.

### CODE REVIEW

**Comment by MSami625** [comment]
Bro the hacker icon which onclick changes the color is not working ..and also if you can fix the login page css.

**Comment by vishnu552** [comment]
can you explain more details about login page like background image color,buttons,height of login page etc

**Comment by MSami625** [comment]
Just whatever it is right now let it be like that only make it responsive and the image used should cover whole background

**Comment by vishnu552** [comment]
ok, hacker icon onclick issue is resolved and I am working on login page.

**Comment by vishnu552** [comment]
login page UI fixed.

**Review by MSami625 — APPROVED** [review]
Nice Work Bro . This issue is now complete if you want  i welcome you to work on other issues.

**Pull request merged**
